import turtle as t
t.shape("turtle")
'''
#보노보노
t.speed(5)
t.pencolor("#000000")
t.width(5)
t.penup()
t.setposition(0,140)
t.pendown()
t.fillcolor("#9de4ff")
t.begin_fill()
t.circle(-200)
t.end_fill()
t.penup()
t.setposition(-150, -18)
t.pendown()
t.width(15)
t.circle(4)
t.penup()
t.setposition(150,-18)
t.pendown()
t.circle(4)
t.penup()
t.setposition(0,-90)
t.width(26)
t.pendown()
t.circle(14)
t.width(7)
t.penup()
t.setposition(14.5, - 90)
t.pendown()
t.fillcolor("#fff0f0")
t.begin_fill()
t.left(60)
t.circle(-30, 150)
t.penup()
t.setposition(14.5 , -90)
t.pendown()
t.circle(30, 150)
t.end_fill()
t.penup()
t.setposition(-14.5, -90)
t.pendown()
t.left(200)
t.fillcolor("#fff0f0")
t.begin_fill()
t.circle(-30, 150)
t.penup()
t.setposition(-14.5, -90)
t.pendown()
t.circle(30, 150)
t.right(200)
t.end_fill()
t.penup()
t.setposition(63, -98)
t.right(60)
t.pendown()
t.forward(40)
t.penup()
t.setposition(58, -98)
t.left(30)
t.pendown()
t.forward(40)
t.right(30)
t.penup()
t.setposition(58, -98)
t.right(30)
t.pendown()
t.forward(40)
t.left(30)

t.penup()
t.setposition(-63, -98)
t.pendown()
t.forward(-40)

t.penup()
t.setposition(-58, -98)
t.left(30)
t.pendown()
t.forward(-40)
t.right(30)

t.penup()
t.setposition(-58, -98)
t.right(30)
t.pendown()
t.forward(-40)
t.left(30)

t.hideturtle()
t.exitonclick()

#스마일
def draw_smile():

    t.fillcolor("yellow")
    t.begin_fill()
    t.circle(100)
    t.end_fill()

    t.penup()
    t.goto(-40, 120)
    t.pendown()
    t.fillcolor("black")
    t.begin_fill()
    t.circle(10)
    t.end_fill()
    t.penup()
    t.goto(40, 120)
    t.pendown()
    t.fillcolor("black")
    t.begin_fill()
    t.circle(10)
    t.end_fill()


    t.penup()
    t.goto(-40, 85)
    t.pendown()
    t.setheading(-60)
    t.circle(40, 120)

draw_smile()

#바둑판
def draw_square(color):
    t.begin_fill()
    t.fillcolor(color)
    for _ in range(4):
        t.forward(25)
        t.right(90)
    t.end_fill()
    t.forward(25)

t.speed(0)

colors = ['red', 'green']
for i in range(8):
    for j in range(8):
        color = colors[(i+j) % 2]
        draw_square(color)
    t.backward(200)
    t.right(90)
    t.forward(25)
    t.left(90)

t.hideturtle()
'''
#오륜기
t.speed(0)
t.pensize(20)

t.circle(100)

t.up()
t.forward(240)
t.down()
t.pencolor('red')
t.circle(100)

t.up()
t.backward(480)
t.down()
t.pencolor('blue')
t.circle(100)

t.up()
t.right(90)
t.forward(120)
t.left(90)
t.forward(120)
t.down()
t.pencolor('yellow')
t.circle(100)

t.up()
t.forward(240)
t.down()
t.pencolor('green')
t.circle(100)